### ISSUE TITLE
FIrst opening of a new wallet opening shows 'API error ...' message

### ISSUE THREAD

**Issue by PeterRounce** [onesandzeros-nz/BoltCardHub#2]
# Bug

* your phone model and OS version
OnePlus Nord

* BoltCardWallet app version (settings->about->scroll down)
Bolt Card Wallet ver 0.1.2 (build 167874118 master)

* self-test passes? Open settings->about->scroll down, tap "Run self-test"
could not find this

* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
4a7690eba203d194

After a new wallet is created, opening the wallet screen for the first time gives:  
`API error: Something went wrong. Please try again later (code 6)`

Everything seems to work fine after that.

![app-2](https://user-images.githubusercontent.com/99006127/225332818-961072bd-20a6-45d0-8d0b-d08936fdfc52.jpg)

**Comment by robertclarkson** [comment]
error traced to the hub
"error getting balance:","cannot get transactions: no onchain address assigned to user"

unsure why this is faulting on the first request

**Comment by PeterRounce** [comment]
looks like the error is coming from this code:

[error getting balance](https://github.com/boltcard/boltcard-lndhub/blob/master/controllers/api.js#L449)

[cannot get transactions: no onchain address assigned to user](https://github.com/boltcard/boltcard-lndhub/blob/master/class/User.js#L600)
