### ISSUE TITLE
set FUNCTION_INTERNAL_API=Enabled

### ISSUE THREAD

**Issue by Retropex** [onesandzeros-nz/BoltCardHub#6]
Hello,

how to set `FUNCTION_INTERNAL_API` to Enabled ? 

Thank you in advance for your help.

**Comment by PeterRounce** [comment]
This is found in the `settings` table of the bolt card service system.

[Bolt Card Service settings](https://github.com/boltcard/boltcard/blob/main/docs/SETTINGS.md)

**Comment by Retropex** [comment]
I admit that it doesn't help me much, am I changing these parameters in the redis database?

**Comment by PeterRounce** [comment]
They are in the Postgres database.

**Comment by Retropex** [comment]
Would it be possible to have more indication?

I have the interface that appears with my domain name And it works.
<img width="1552" alt="Capture d’écran 2023-08-30 à 01 29 40" src="https://github.com/boltcard/boltcard-lndhub/assets/74937347/8e4ef4f9-cf31-44f9-b1f1-8ad2efe3bb82">


But when I press Connect bolt card I get this error. (port 9001 is correctly redirected and `ufw` authorizes port 9001)

<img width="414" alt="image" src="https://github.com/boltcard/boltcard-lndhub/assets/74937347/ceea24ff-bda2-43cc-aa80-7452dd7d26da">

I imagine that it's because `FUNCTION_INTERNAL_API` is not activated but I absolutely don't know how to do SQL.
